# Generated by Django 4.1.2 on 2022-10-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Calculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_one", models.IntegerField()),
                ("number_two", models.IntegerField()),
                ("result", models.IntegerField()),
            ],
        ),
    ]
